name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      uses: sergioramos/yarn-actions/install@master
      with:
        frozen-lockfile: true
    - name: build
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: build
    - name: test
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test
